FROM ubuntu:20.04

RUN apt-get update
RUN apt-get -qq dist-upgrade
RUN apt-get -qq install software-properties-common
RUN apt-get -qq install default-jre-headless build-essential git unzip zip subversion
RUN apt-get install -qq p7zip-full
